// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmDyK4ZtGKr3_C7bjiXzdfs4tMoQBV5OM',
    appId: '1:688773005235:web:e969ee949593f8bdab15c6',
    messagingSenderId: '688773005235',
    projectId: 'jolu-trip-d529a',
    authDomain: 'jolu-trip-d529a.firebaseapp.com',
    storageBucket: 'jolu-trip-d529a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyn3R_KIhlKqes4Zg58w9_Wsz0CHDsh_4',
    appId: '1:688773005235:android:95f540934b171313ab15c6',
    messagingSenderId: '688773005235',
    projectId: 'jolu-trip-d529a',
    storageBucket: 'jolu-trip-d529a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4UVFzt6VlfYT0P8AQCmLOEHRvrpjspGk',
    appId: '1:688773005235:ios:8b227dfcb41a6720ab15c6',
    messagingSenderId: '688773005235',
    projectId: 'jolu-trip-d529a',
    storageBucket: 'jolu-trip-d529a.firebasestorage.app',
    iosBundleId: 'com.example.joluTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4UVFzt6VlfYT0P8AQCmLOEHRvrpjspGk',
    appId: '1:688773005235:ios:8b227dfcb41a6720ab15c6',
    messagingSenderId: '688773005235',
    projectId: 'jolu-trip-d529a',
    storageBucket: 'jolu-trip-d529a.firebasestorage.app',
    iosBundleId: 'com.example.joluTrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmDyK4ZtGKr3_C7bjiXzdfs4tMoQBV5OM',
    appId: '1:688773005235:web:e115531031fde67bab15c6',
    messagingSenderId: '688773005235',
    projectId: 'jolu-trip-d529a',
    authDomain: 'jolu-trip-d529a.firebaseapp.com',
    storageBucket: 'jolu-trip-d529a.firebasestorage.app',
  );

}